apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4001
          env:
            - name: DATABASE_URL
              value: postgres://finance:finance@postgres-service:5432/finance_tracker
            - name: JWT_SECRET
              value: replace-with-your-actual-secret