apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion-service
  ports:
    - port: {{ .Values.ingestionService.port }}
      targetPort: {{ .Values.ingestionService.port }}