apiVersion: v1
kind: Service
metadata:
  name: reporting-service
spec:
  selector:
    app: reporting-service
  ports:
    - port: {{ .Values.reportingService.port }}
      targetPort: {{ .Values.reportingService.port }}